openapi: 3.0.4
info:
  title: Mesh Task Account
  contact:
    email: roman@kamalium.com
  version: 0.0.1
servers:
  - url: /
tags:
  - name: User
    description: User Operations
  - name:  Account
    description: Account Operations
paths:
  /user/generate_jwt:
    post:
      tags:
        - User
      operationId: userGenerateJwt
      requestBody:
        $ref: '#/components/requestBodies/UserTokenRequest'
      responses:
        '200':
          $ref: '#/components/responses/UserTokenResponse'

  /account/addbalance:
    post:
      tags:
        - Account
      operationId: accountAddBalance
      requestBody:
        $ref: '#/components/requestBodies/AccountAddBalanceRequest'
      responses:
        '200':
          $ref: '#/components/responses/AccountAddBalanceResponse'

  /account/transfer:
    post:
      tags:
        - Account
      operationId: accountTransfer
      requestBody:
        $ref: '#/components/requestBodies/AccountTransferRequest'
      responses:
        '200':
          $ref: '#/components/responses/AccountTransferResponse'


components:
  requestBodies:
    AccountTransferRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountTransferRequestSchema'
    AccountAddBalanceRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountAddBalanceRequestSchema'
    UserTokenRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserTokenRequestSchema'


  responses:
    AccountTransferResponse:
      description: Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountTransferResponseSchema'
    AccountAddBalanceResponse:
      description: Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountAddBalanceResponseSchema'
    UserTokenResponse:
      description: Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserTokenResponseSchema'


  schemas:
    AccountAddBalanceRequestSchema:
      type: object
      required:
        - id
        - balance
      properties:
        id:
          type: integer
          format: int64
        balance:
          type: number
          format: double

    AccountAddBalanceResponseSchema:
      type: object
      required:
        - id
        - userId
        - balance
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        balance:
          type: number
          format: double

    AccountTransferRequestSchema:
      type: object
      required:
        - srcId
        - dstId
        - amount
      properties:
        srcId:
          type: integer
          format: int64
        dstId:
          type: integer
          format: int64
        amount:
          type: number
          format: double

    AccountTransferResponseSchema:
      type: object
      required:
        - status
      properties:
        status:
          type: string

    UserTokenRequestSchema:
      type: object
      required:
        - userId
      properties:
        userId:
          type: integer
          format: int64

    UserTokenResponseSchema:
      type: object
      required:
        - token
      properties:
        token:
          type: string

