openapi: 3.0.4
info:
  title: Mesh Task Account
  contact:
    email: roman@kamalium.com
  version: 0.0.1
servers:
  - url: /
tags:
  - name: User
    description: User Operations
  - name:  Account
    description: Account Operations
paths:
  /user/generate_jwt:
    post:
      tags:
        - User
      operationId: userGenerateJwt
      requestBody:
        $ref: '#/components/requestBodies/UserTokenRequest'
      responses:
        '200':
          $ref: '#/components/responses/UserTokenResponse'

  /user/addphone:
    post:
      tags:
        - User
      operationId: userAddPhone
      requestBody:
        $ref: '#/components/requestBodies/UserAddPhoneRequest'
      responses:
        '200':
          $ref: '#/components/responses/UserAddPhoneResponse'

  /user/changephone:
    post:
      tags:
        - User
      operationId: userChangePhone
      requestBody:
        $ref: '#/components/requestBodies/UserChangePhoneRequest'
      responses:
        '200':
          $ref: '#/components/responses/UserChangePhoneResponse'

  /user/delete/{id}:
    delete:
      operationId: userDeletePhone
      tags:
        - User
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK


  /account/addbalance:
    post:
      tags:
        - Account
      operationId: accountAddBalance
      requestBody:
        $ref: '#/components/requestBodies/AccountAddBalanceRequest'
      responses:
        '200':
          $ref: '#/components/responses/AccountAddBalanceResponse'

  /account/transfer:
    post:
      tags:
        - Account
      operationId: accountTransfer
      requestBody:
        $ref: '#/components/requestBodies/AccountTransferRequest'
      responses:
        '200':
          $ref: '#/components/responses/AccountTransferResponse'


components:
  requestBodies:
    UserChangePhoneRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserChangePhoneRequestSchema'
    UserAddPhoneRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserAddPhoneRequestSchema'
    AccountTransferRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountTransferRequestSchema'
    AccountAddBalanceRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountAddBalanceRequestSchema'
    UserTokenRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserTokenRequestSchema'


  responses:
    UserChangePhoneResponse:
      description: Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserChangePhoneResponseSchema'
    UserAddPhoneResponse:
      description: Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserAddPhoneResponseSchema'
    AccountTransferResponse:
      description: Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountTransferResponseSchema'
    AccountAddBalanceResponse:
      description: Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountAddBalanceResponseSchema'
    UserTokenResponse:
      description: Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserTokenResponseSchema'


  schemas:
    UserChangePhoneRequestSchema:
      type: object
      required:
        - id
        - phone
      properties:
        id:
          type: integer
          format: int64
        phone:
          type: string
    UserChangePhoneResponseSchema:
      type: object
      required:
        - id
        - userId
        - phone
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        phone:
          type: string

    UserAddPhoneRequestSchema:
      type: object
      required:
        - phone
      properties:
        phone:
          type: string
    UserAddPhoneResponseSchema:
      type: object
      required:
        - id
        - userId
        - phone
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        phone:
          type: string


    AccountAddBalanceRequestSchema:
      type: object
      required:
        - id
        - balance
      properties:
        id:
          type: integer
          format: int64
        balance:
          type: number
          format: double

    AccountAddBalanceResponseSchema:
      type: object
      required:
        - id
        - userId
        - balance
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        balance:
          type: number
          format: double

    AccountTransferRequestSchema:
      type: object
      required:
        - srcId
        - dstId
        - amount
      properties:
        srcId:
          type: integer
          format: int64
        dstId:
          type: integer
          format: int64
        amount:
          type: number
          format: double

    AccountTransferResponseSchema:
      type: object
      required:
        - status
      properties:
        status:
          type: string

    UserTokenRequestSchema:
      type: object
      required:
        - userId
      properties:
        userId:
          type: integer
          format: int64

    UserTokenResponseSchema:
      type: object
      required:
        - token
      properties:
        token:
          type: string

  parameters:
    id:
      in: path
      required: true
      name: id
      schema:
        type: integer
        format: int64















